Libraries

```{r}
library(tidyverse)
library(lme4)
library(pscl)
```

Load data from master.csv

```{r}
df <- read_csv("Notebooks\\Machine-Learning\\master.csv")

df_standardized <- df|>
    mutate(MU_s = scale(MU),
    Span_s = scale(Span),
    Area_s = scale(Area),
    Circumference_s = scale(Circumference),
    MCS_s = scale(MCS),
    CoA_s = scale(CoA),
    QAPass = AD > ADPass)
```

Linear Model

```{r}
model.1 <- glm(QAPass ~ MU_s + Span_s + Area_s + Circumference_s + MCS_s + CoA_s, data = df_standardized, family="binomial")

summary(model.1)

preds <- predict(model.1, df_standardized) > 0.5

mean(preds == df_standardized$QAPass)

df_standardized$preds <- preds
```

```{r}
# goodness of fit

1 - pchisq(model.1$deviance, 757)

pR2(model.1)["McFadden"]

```


```{r}
# Predict classes using the model
predicted_classes <- ifelse(predict(model.1, type = "response") > 0.5, 1, 0)

# Assuming your actual classes are stored in a vector called actual_classes
# Construct the confusion matrix
conf_matrix <- table(df_standardized$QAPass, predicted_classes)

# Print the confusion matrix
print(conf_matrix)

# Calculate accuracy
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
print(paste("Accuracy:", accuracy))
```

Individual Statistical Significance

```{r}
model.MU <- glm(QAPass ~ MU_s, data = df_standardized, family="binomial")

summary(model.MU)
#-------------
model.Span <- glm(QAPass ~ Span_s, data = df_standardized, family="binomial")

summary(model.Span)
# ------------------
model.Area <- glm(QAPass ~ Area_s, data = df_standardized, family="binomial")

summary(model.Area)
# ------------------
model.Circumference <- glm(QAPass ~ Circumference_s, data = df_standardized, family="binomial")

summary(model.Circumference)
#---------------------------
model.MCS <- glm(QAPass ~ MCS_s, data = df_standardized, family="binomial")

summary(model.MCS)
#---------------------------
model.CoA <- glm(QAPass ~ CoA_s, data = df_standardized, family="binomial")

summary(model.CoA)
```


Multi-level model

```{r}

multi_level_df <- df_standardized |> filter(!is.na(PID))|>mutate(PID2 = paste(multi_level_df$PID, multi_level_df$QADate))

model.2 <- glmer(AD<ADPass ~ MU_s + Span_s + Area_s + Circumference_s + MCS_s + (1|PID2), data = multi_level_df, family="binomial")

summary(model.2)

preds <- predict(model.2, multi_level_df) > 0.5

mean(preds == multi_level_df$QAPass)
```

```{r}
df2 <- read_csv("Notebooks\\Machine-Learning\\master2.csv")

df2<- df2|>
    mutate(QAPass = AD > ADPass)


```

lasso 

```{r}
library(glmnet)
fit <- glmnet(df_standardized |> select(MU_s, Area_s, Span_s, Circumference_s, MCS_s, CoA_s), df_standardized$AD < df_standardized$ADPass, family = "binomial", alpha = 1)
plot(fit, label = TRUE)
coef(fit, s = 0.0075)
```

Correlations
```{r}
library(corrplot)
corrplot(cor(df_standardized|>select(Area_s, Circumference_s, CoA_s, Span_s, MU_s, MCS_s)))
```

Confusion Matrix
```{r}
confusion_matrix <- table(multi_level_df$QAPass, preds)

# Print confusion matrix
print(confusion_matrix)
```